services:
  fastapi:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../src/who_ring_api/config/.env
    depends_on:
      - redis

  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - fastapi

  redis:
    image: redis:7
    ports:
      - "6379:6379"
