services:
  fastapi:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../src/who_ring_api/config/.env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
